# Generated by Django 5.2.17 on 2026-09-05 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_payment_booking_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='movies_book_booked__a7ab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'booked_at'], name='movies_book_theater_a2fd03_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_cancelled'], name='movies_book_is_canc_9ead74_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='movies_paym_created_5e9beb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='movies_paym_status_5316c9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='movies_paym_status_8acdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'is_booked'], name='movies_seat_theater_7e5f1d_idx'),
        ),
    ]
