# Generated by Django 5.2.17 on 2026-09-17 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_booking_cancelled_at_booking_is_cancelled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='movies_book_is_canc_9ead74_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_status_5316c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_status_8acdf7_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_booked_at_idx',
            old_name='movies_book_booked__a7ab7e_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_theater_date_idx',
            old_name='movies_book_theater_a2fd03_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payment_created_at_idx',
            old_name='movies_paym_created_5e9beb_idx',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at', 'is_cancelled'], name='booking_date_cancel_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'booked_at'], name='booking_movie_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at', 'status'], name='payment_date_status_idx'),
        ),
    ]
